### ISSUE TITLE
'Plotter' object has no attribute 'plot_Rt_types'

### ISSUE THREAD

**Issue by lauramiron** [covid19-model/simulator#3]
It looks like the function `plotter.plot_Rt_types()` was removed by commit 88328a4a0ffe61a80311e492d4d6598f9ec5d615 which adds functions for computing the daily Rts.  There are still several places in sim/experiments.ipynb that call `plotter.plot_Rt_types()`.  Is the new function `plotter.plot_daily_rts()` intended to replace `plotter.plot_Rt_types()`?

**Comment by trouleau** [comment]
Hello,
That is indeed a bug introduced in this commit. We updated the way effective reproduction numbers are computed to report these estimates on the updated version of our paper but I missed them in `sim/experiments.ipynb`. Thank you for pointing this out and apologies. This should now be fixed in 89b7b5dad7716b6461fe0bb574bc7c1304cad656.
